### ISSUE TITLE
Clipping temperate data with a boundary 

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/heatwaves#1]
We already have heatwaves days calculated on these [data files](https://worldbankgroup.sharepoint.com.mcas.ms/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=Yvwh8r&cid=fccdf23e%2D94d5%2D48bf%2Db75d%2D0af291138bde&FolderCTID=0x012000CFAB9FF0F938A64EBB297E7E16BDFCFD&id=%2Fteams%2FDevelopmentDataPartnershipCommunity%2DWBGroup%2FShared%20Documents%2FProjects%2FHeatwaves%20Data%20Collaborative%2FData%2Fremotesensing%2Fhwdi%5F5degC%2Fhwdi%5Fydrunmean3&viewid=80cdadb3%2D8bb3%2D47ae%2D8b18%2Dc1dd89c373c5) and we need to clip a boundary for Chennai, IN.

**Comment by g4brielvs** [comment]
@SahitiSarva I'll open a PR to address this in a bit.

**Comment by g4brielvs** [comment]
@SahitiSarva Where is `india_district/sh819zz8121.shp`? Is it on [Data](https://worldbankgroup.sharepoint.com/:f:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Projects/Heatwaves%20Data%20Collaborative/Data?csf=1&web=1&e=ki9HwC)?

**Comment by SahitiSarva** [comment]
Yes, its [here](https://worldbankgroup.sharepoint.com.mcas.ms/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Forms/AllItems.aspx?csf=1&web=1&e=Yvwh8r&cid=fccdf23e%2D94d5%2D48bf%2Db75d%2D0af291138bde&FolderCTID=0x012000CFAB9FF0F938A64EBB297E7E16BDFCFD&id=%2Fteams%2FDevelopmentDataPartnershipCommunity%2DWBGroup%2FShared%20Documents%2FProjects%2FHeatwaves%20Data%20Collaborative%2FData%2Findia%5Fdistrict&viewid=80cdadb3%2D8bb3%2D47ae%2D8b18%2Dc1dd89c373c5)

**Comment by SahitiSarva** [comment]
Although the clipping happens, it is not exactly in the polygon that is used as input. A few stray lat lon values appear. is this because it is taking the nearest lat lon values to the polygon?
