### ISSUE TITLE
Remove compromised token

### ISSUE THREAD

**Issue by g4brielvs** [datapartnership/heatwaves#11]
The commit 7263b336adb410e81b5b0225392486d04378b1d5 exposed the Tomorrow.io API key. The API key has to be revoked.

**Comment by g4brielvs** [comment]
@SahitiSarva Would you please write to Tomorrow.io to see how the token will be revoked and how the Partnership can gain access to the account. It doesn't seem that this token was created from the [Partnership account](https://worldbankgroup.sharepoint.com/:w:/r/teams/DevelopmentDataPartnershipCommunity-WBGroup/Shared%20Documents/Operations/Data%20Partners/Tomorrow.io/Tomorrow.io%20Data%20Management%20Plan%20.docx?d=w35965db1526a457485a5cdecc38f5b80&csf=1&web=1&e=ZkiEY4).

**Comment by SahitiSarva** [comment]
It is created from our old partnership account. The token and account have now been revoked.
