### ISSUE TITLE
Querying tomorrow.io

### ISSUE THREAD

**Issue by SahitiSarva** [datapartnership/heatwaves#9]
I'm seeing the below error when I try to query a polygon - 
'code': 403003,
  'type': 'Forbidden Action',
  'message': 'The plan is restricted and cannot perform this action. Adjust action and try again: Querying polygon or linestring locations is not allowed'

I believe this implies that our current API does not support getting data for a polygon. @g4brielvs do you think we should request for this?

**Comment by g4brielvs** [comment]
@SahitiSarva Thanks! Please let me take a look and I'll report back later today. In addition, we'll have to address #11.

**Comment by g4brielvs** [comment]
@SahitiSarva It seems that the previous Tomorrow.io API token was not authorized, but the new one works well. Closing this issue.
